### ISSUE TITLE
Cannot eager load users with trashed

### ISSUE THREAD

**Issue by rmasters** [rmasters/culpa#11]
Might be a Laravel issue, the following does not work:

```
class Post extends Eloquent {
    public function createdBy() {
        // Culpa\CreatedBy
        return $this->belongsTo('User')->withTrashed();
    }
}

Post::with('createdBy')->get();
```

Results in "Invalid argument supplied for foreach()" in Illuminate/Database/Eloquent/Builder.php:388 (`$this->query->wheres` is null).

**Comment by rmasters** [comment]
Found this upstream in laravel/laravel#2225

**Comment by rmasters** [comment]
Waiting on laravel/framework#2556

**Comment by afarazit** [comment]
You can close this, it's fixed https://github.com/laravel/framework/pull/2556#issuecomment-27250334
